export const languageList = [
    {value: 'en', position: '-133px', name: 'English'},
    {value: 'cn', position: '0', name: '中文'},
    {value: 'de', position: '-19px', name: 'Deutsch'},
    {value: 'fr', position: '-114px', name: 'Français'},
    {value: 'sp', position: '-76px', name: 'Español'},
    {value: 'it', position: '-171px', name: 'Italiano'},
    {value: 'ja', position: '-190px', name: '日本語'},
    {value: 'ar', position: '-57px', name: 'العربية'},
    {value: 'pt', position: '-285px', name: 'Português'},
    {value: 'tr', position: '-342px', name: 'Türkçe'},
    {value: 'no', position: '-247px', name: 'Norsk'},
    {value: 'sv', position: '-323px', name: 'Svenska'},
    {value: 'fi', position: '-95px', name: 'Suomi'},
    {value: 'da', position: '-38px', name: 'Dansk'},
    {value: 'nl', position: '-228px', name: 'Nederlands'},
    {value: 'ko', position: '-209px', name: '한국어'},
    {value: 'ru', position: '-304px', name: 'Русский'},
]

